#!/bin/bash

debug_bashrc "Setting up PS1"

PS1=

if [ "$color_prompt" = yes ]; then
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]$(last_cmd)\[\033[00m\]\[\033[01;34m\]\w\[\033[00m\] \[\033[01;30m\]$(vcs_echo "[")\[$(color_vcs_branch)\]$(formatted_vcs_branch 1)\[\033[01;30m\]$(vcs_echo "]")\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}$(last_cmd)\u@\h:\w$ [$(formatted_vcs_branch)]\$ '
fi

if [[ -n "$SSH_CONNECTION" || -n "$SUDO_USER" ]]; then
    if [ "$color_prompt" = yes ]; then
        PS1="\[\033[32m\]\u@\h\[\033[0m\] $PS1"
    else
        PS1="[\u@\h] $PS1"
    fi
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    #PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    :
    ;;
*)
    ;;
esac


